Repository openPMD/openPMD-viewer, pull requests merged in 2018-05, with the labels that each got.

#190 More options to get_emittance
  opmd_viewer/addons/pic/lpa_diagnostics.py
Labels: feature

#199 Close #196 Vertical axis does not work for for 1D histogram
  opmd_viewer/openpmd_timeseries/main.py
  opmd_viewer/openpmd_timeseries/plotter.py
Labels: bug, interactive

#202 Update tutorial notebooks
  tutorials/1_Introduction-to-the-API.ipynb
  tutorials/2_Specific-field-geometries.ipynb
  tutorials/3_Introduction-to-the-GUI.ipynb
  tutorials/4_Particle_selection.ipynb
  tutorials/5_Laser-plasma_tools.ipynb
Labels: refactoring

#195 Allow slicing along several directions
  CHANGELOG.md
  conda_recipe/meta.yaml
  opmd_viewer/__version__.py
  opmd_viewer/addons/pic/lpa_diagnostics.py
  opmd_viewer/openpmd_timeseries/data_reader/field_metainfo.py
  opmd_viewer/openpmd_timeseries/data_reader/field_reader.py
  opmd_viewer/openpmd_timeseries/data_reader/utilities.py
  opmd_viewer/openpmd_timeseries/interactive.py
  opmd_viewer/openpmd_timeseries/main.py
Labels: breaking API change

#212 Remove the (useless) argument `output`
  opmd_viewer/openpmd_timeseries/main.py
Labels: breaking API change
