Repository openPMD/openPMD-viewer, pull requests merged in 2023-06, with the labels that each got.

#372 Adding attributes to the FieldMetaInformation object
  openpmd_viewer/addons/pic/lpa_diagnostics.py
  openpmd_viewer/openpmd_timeseries/data_reader/h5py_reader/field_reader.py
  openpmd_viewer/openpmd_timeseries/data_reader/io_reader/field_reader.py
  openpmd_viewer/openpmd_timeseries/field_metainfo.py
  tests/test_tutorials.py
Labels: feature

#375 Add readthedoc configuration
  .readthedocs.yaml
  docs/requirements.txt
  docs/source/api_reference/particle_tracking.rst
Labels: documentation

#378 setup.py: no upper version of openPMD-api
  setup.py
Labels: install
