Repository openPMD/openPMD-viewer, pull requests merged in 2023-08, with the labels that each got.

#383 Impose that user always passes iteration or t
  openpmd_viewer/openpmd_timeseries/main.py
Labels: bug

#382 Docs: Improve tutorials by adding basic analysis functions
  docs/source/tutorials/1_Introduction-to-the-API.ipynb
Labels: documentation

#359 Improve get_laser_waist
  openpmd_viewer/addons/pic/lpa_diagnostics.py
Labels: feature

#387 Python 3.8+
  .github/workflows/unix.yml
  setup.py
Labels: documentation, install

#386 Update version number and CHANGELOG.md
  CHANGELOG.md
  openpmd_viewer/__version__.py
Labels: documentation
